image:
  file: .gitpod.Dockerfile

# TODO : Develop change one place, apply to all repositories for tasks, fetch tasks from base images - use docker registry api or Dockerfile (via. parse) for this, list these additional commands in secondary .gitpod.yml - which is git ignored, the program to fetch tasks is the init command of every gitpod image, and the .gitpod.yml only contains the image specific tasks
# TODO : fetch user specific compliment tasks (eg. google-chrome) from base images - use docker registry api or Dockerfile (via. parse) for this, list these additional commands in ternary .gitpod.yml - which is git ignored, the program to fetch tasks is the init command of every gitpod image, and the .gitpod.yml only contains the image specific tasks
# tasks:
  # - init: /usr/bin/start-vnc-session.sh
  # - command: zsh
  # - command: git clone --depth 1 "https://github.com/Baneeishaque/gitpod-workspace-full-vnc-1366x768-tint2-pcmanfm-zsh-android-studio.git" android-studio-config && mkdir -p ~/.config/Google && ln -s `pwd`/android-studio-config/AndroidStudio4.1-config ~/.config/Google/AndroidStudio4.1 && mkdir -p ~/.local/share/Google && ln -s `pwd`/android-studio-config/AndroidStudio4.1-local ~/.local/share/Google/AndroidStudio4.1 && cd /usr/local/android-studio/bin/ && ./studio.sh
  # - command: git clone --depth 1 "https://github.com/Baneeishaque/gitpod-workspace-full-vnc-1366x768-tint2-pcmanfm-zsh-android-studio-gh-chrome-intellij-idea.git" intellij-idea-config && mkdir -p ~/.config/JetBrains && ln -s `pwd`/intellij-idea-config/IntelliJIdea2021.1-config ~/.config/JetBrains/IntelliJIdea2021.1 && mkdir -p ~/.local/share/JetBrains && ln -s `pwd`/android-studio-config/IntelliJIdea2021.1-local ~/.local/share/JetBrains/IntelliJIdea2021.1 && cd /usr/local/idea-IU-211.6693.111/bin/ && ./idea.sh
  # - command: git clone --depth 1 "https://github.com/Baneeishaque/gitpod-workspace-full-vnc-1366x768-tint2-pcmanfm-zsh-android-studio-gh-chrome-intellij-idea-pycharm.git" pycharm-config && mkdir -p ~/.config/JetBrains && ln -s `pwd`/pycharm-config/Pycharm2021.1-config ~/.config/JetBrains/PyCharm2021.1 && mkdir -p ~/.local/share/JetBrains && ln -s `pwd`/pycharm-config/Pycharm2021.1-local ~/.local/share/JetBrains/PyCharm2021.1 && cd /usr/local/pycharm-2021.1/bin/ && ./pycharm.sh
  # TODO : Change this
  # - command: mkdir -p ~/.config/Google && ln -s `pwd`/AndroidStudioPreview2020.3-config ~/.config/Google/AndroidStudioPreview2020.3 && mkdir -p ~/.local/share/Google && ln -s `pwd`/AndroidStudioPreview2020.3-local ~/.local/share/Google/AndroidStudioPreview2020.3 && cd /usr/local/android-studio-canary/bin/ && ./studio.sh

  # - init: gh auth login
  # - command: google-chrome --disable-dev-shm-usage

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
  - port: 6942
    onOpen: ignore
  - port: 6943
    onOpen: ignore
  - port: 6944
    onOpen: ignore
  - port: 6945
    onOpen: ignore
